blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ GitHub Discussions (Questions & Ideas)
    url: https://github.com/cataseven/Keenetic-Router-Pro/discussions
    about: Please ask general questions or share ideas here.
